[package]
name = "egg-for-lean"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
egg = "0.10"
itertools = "0.14.0"
lazy_static = "1.5.0"
libc = "0.2"
log = "0.4.29"

[build-dependencies]
cc = "1.0"
